name: Codecov

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Run coverage
        run: make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          file: coverage-filtered.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}